import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#F4F7FB' },
  pageShell: { flex: 1 },
  pageShellWeb: { alignSelf: 'center', maxWidth: 1280, paddingHorizontal: 24, paddingVertical: 24, width: '100%' },
  header: {
    backgroundColor: '#1E3A8A',
    borderBottomColor: '#1E40AF',
    borderBottomWidth: 1,
    paddingBottom: 18,
    paddingHorizontal: 20,
    paddingTop: 14,
  },
  headerWeb: { borderRadius: 18, paddingHorizontal: 28, paddingVertical: 24 },
  headerRow: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between' },
  headerActions: { alignItems: 'center', flexDirection: 'row', gap: 8 },
  headerRight: { alignItems: 'center', flexDirection: 'row', gap: 10, marginTop: 12 },
  headerTitle: { color: '#fff', fontSize: 24, fontWeight: '800' },
  headerEyebrow: { color: '#BFDBFE', fontSize: 12, fontWeight: '700', marginBottom: 4, textTransform: 'uppercase' },
  roleBadge: { backgroundColor: '#DBEAFE', borderRadius: 16, color: '#1E3A8A', fontSize: 12, fontWeight: '600', paddingHorizontal: 12, paddingVertical: 6 },
  logoutButton: { backgroundColor: '#EFF6FF', borderRadius: 8, paddingHorizontal: 12, paddingVertical: 7 },
  logoutText: { color: '#1D4ED8', fontSize: 14, fontWeight: '600' },
  loadingContainer: { alignItems: 'center', flex: 1, justifyContent: 'center' },
  contentShell: { flex: 1 },
  contentShellWeb: { flexDirection: 'row', gap: 20, marginTop: 20 },
  sidebarCard: { backgroundColor: '#FFFFFF', borderColor: '#D8E2EA', borderRadius: 18, borderWidth: 1, flexShrink: 0, padding: 22, width: 300 },
  sidebarLabel: { color: '#64748B', fontSize: 12, fontWeight: '800', marginBottom: 8, textTransform: 'uppercase' },
  sidebarRole: { color: '#111827', fontSize: 24, fontWeight: '800', marginBottom: 10 },
  sidebarCopy: { color: '#475569', fontSize: 14, lineHeight: 22 },
  sidebarMetricRow: { flexDirection: 'row', gap: 12, marginTop: 22 },
  metricCard: { backgroundColor: '#EFF6FF', borderRadius: 14, flex: 1, padding: 16 },
  metricValue: { color: '#1D4ED8', fontSize: 26, fontWeight: '800' },
  metricLabel: { color: '#475569', fontSize: 12, fontWeight: '700', marginTop: 4, textTransform: 'uppercase' },
  feedCard: { flex: 1 },
  feedCardWeb: { backgroundColor: '#FFFFFF', borderColor: '#D8E2EA', borderRadius: 18, borderWidth: 1, minHeight: 520, overflow: 'hidden' },
  listContent: { padding: 14, paddingBottom: 28 },
  notificationItem: { backgroundColor: '#fff', borderColor: '#D8E2EA', borderRadius: 8, borderWidth: 1, marginBottom: 10, padding: 15, position: 'relative' },
  notificationItemWeb: { marginBottom: 12, padding: 18 },
  unreadNotification: { backgroundColor: '#EFF6FF', borderColor: '#1D4ED8' },
  notificationHeader: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 8 },
  notificationTitle: { color: '#111827', flex: 1, fontSize: 16, fontWeight: '700' },
  notificationTime: { color: '#888', fontSize: 12, marginLeft: 10 },
  notificationBody: { color: '#4B5563', fontSize: 14, lineHeight: 20 },
  statusText: { alignSelf: 'flex-start', backgroundColor: '#EEF2FF', borderRadius: 8, color: '#1D4ED8', fontSize: 12, fontWeight: '700', marginTop: 8, paddingHorizontal: 8, paddingVertical: 4 },
  unreadDot: { backgroundColor: '#1D4ED8', borderRadius: 4, height: 8, position: 'absolute', right: 10, top: 10, width: 8 },
  emptyContainer: { alignItems: 'center', justifyContent: 'center', paddingVertical: 80 },
  emptyText: { color: '#111827', fontSize: 18, fontWeight: '700', marginBottom: 8, textAlign: 'center' },
  emptySubtext: { color: '#6B7280', fontSize: 14, lineHeight: 22, maxWidth: 420, textAlign: 'center' },
});
