import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: '#F4F7FB' },
  container: { flexGrow: 1, justifyContent: 'center', paddingHorizontal: 24, paddingVertical: 28 },
  webContainer: { alignItems: 'center', paddingHorizontal: 32, paddingVertical: 40 },
  authShell: { width: '100%' },
  authShellWeb: {
    backgroundColor: '#FFFFFF',
    borderColor: '#D8E2EA',
    borderRadius: 18,
    borderWidth: 1,
    flexDirection: 'row',
    maxWidth: 1160,
    minHeight: 720,
    overflow: 'hidden',
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 20 },
    shadowOpacity: 0.08,
    shadowRadius: 40,
  },
  webHero: { backgroundColor: '#0F3D99', flex: 1, justifyContent: 'space-between', paddingHorizontal: 38, paddingVertical: 42 },
  webHeroEyebrow: { color: '#BFDBFE', fontSize: 12, fontWeight: '800', letterSpacing: 0.4, textTransform: 'uppercase' },
  webHeroTitle: { color: '#FFFFFF', fontSize: 38, fontWeight: '800', lineHeight: 46, marginTop: 18 },
  webHeroBody: { color: '#DBEAFE', fontSize: 16, lineHeight: 26, marginTop: 20, maxWidth: 430 },
  webFeatureList: { gap: 14, marginTop: 32 },
  webFeatureItem: { color: '#EFF6FF', fontSize: 15, lineHeight: 22 },
  formCard: { width: '100%' },
  formCardWeb: { flex: 0.95, justifyContent: 'center', maxWidth: 470, paddingHorizontal: 42, paddingVertical: 42 },
  eyebrow: { color: '#2563EB', fontSize: 13, fontWeight: '800', marginBottom: 8, textAlign: 'center', textTransform: 'uppercase' },
  eyebrowWeb: { textAlign: 'left' },
  title: { color: '#111827', fontSize: 30, fontWeight: '800', marginBottom: 8, textAlign: 'center' },
  titleWeb: { textAlign: 'left' },
  subtitle: { color: '#4B5563', fontSize: 15, lineHeight: 22, marginBottom: 26, textAlign: 'center' },
  subtitleWeb: { textAlign: 'left' },
  input: {
    backgroundColor: '#fff',
    borderColor: '#CBD5E1',
    borderRadius: 8,
    borderWidth: 1,
    color: '#111827',
    fontSize: 16,
    marginBottom: 15,
    paddingHorizontal: 16,
    paddingVertical: 15,
  },
  roleContainer: { marginBottom: 20 },
  label: { color: '#111827', fontSize: 16, marginBottom: 8 },
  roleButtons: { flexDirection: 'row', gap: 10 },
  roleButton: {
    alignItems: 'center',
    backgroundColor: '#fff',
    borderColor: '#CBD5E1',
    borderRadius: 8,
    borderWidth: 1,
    flex: 1,
    padding: 15,
  },
  roleButtonActive: { backgroundColor: '#1D4ED8', borderColor: '#1D4ED8' },
  roleButtonText: { color: '#333', fontWeight: '600' },
  roleButtonTextActive: { color: '#fff' },
  button: { alignItems: 'center', backgroundColor: '#1D4ED8', borderRadius: 8, marginTop: 10, padding: 15 },
  buttonText: { color: '#fff', fontSize: 16, fontWeight: '700' },
  linkText: { color: '#1D4ED8', marginTop: 20, textAlign: 'center' },
  secondaryLinkText: { color: '#1D4ED8', fontWeight: '700', marginTop: 14, textAlign: 'center' },
});
